### ISSUE TITLE
Byfl 3.9 Branch does not Compile with LLVM 3.9

### ISSUE THREAD

**Issue by nmhamster** [lanl/Byfl#18]
I am guessing that this is an LLVM IR issue?

Steps:

(1) Checkout LLVM using the 3.9 branch from the SVN
(2) Build LLVM and install
(3) Put LLVM in path and configure Byfl
(4) Run `make`

```
../../../lib/bytesflops/init.cpp: In member function ‘void bytesflops_pass::BytesFlops::track_global_variables(llvm::Module*)’:
../../../lib/bytesflops/init.cpp:140:14: error: ‘class llvm::GlobalVariable’ has no member named ‘getDebugInfo’
       gv_var.getDebugInfo(gvs);
              ^
```

**Comment by spakin** [comment]
That looks like a mismatch between the Byfl version and the LLVM version.  Be sure to use the [`llvm-3.9`](https://github.com/lanl/Byfl/tree/llvm-3.9) branch of Byfl if you're using a 3.9.x branch of LLVM/Clang.

**Comment by nmhamster** [comment]
@spakin you are correct, I removed the original checkout with the issues that I have in issue #2. Sorry for the false alarm and your help!
